### ISSUE TITLE
API #9 out of 10

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/https-hollandgrouphomeconcierge.com-#1]
@codextiny
Please add API functionality to[ this new site ](https://hollandgrouphomeconcierge.com/)

Credentials:
U: [support@homeowner.ai](mailto:support@homeowner.ai)
PW: M!l3st0nesL@bs

- Update search bar with API functionality
- Add pop up form to Get Started Button in header on home page
- Add pop up form to CTA button in pre-footer on home page

**Comment by Faizan-Ramzan** [comment]
@shannonbaldwin 

Done from our side, please check
